version: '3.8'

networks:
  monitoring-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data:

services:
  # 1. Aplikasi Target (Buatan Person 1)
  app:
    build: 
      context: ../app
      dockerfile: Dockerfile
    container_name: observability-app
    ports:
      - "3000:3000"
    networks:
      - monitoring-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 2. Prometheus Service
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus_data:/prometheus
    # Command ini agar prometheus bisa jalan tanpa config file sementara waktu 
    # (nanti file confignya dibuat oleh Person 5)
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    networks:
      - monitoring-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:9090/-/healthy"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 3. Grafana Service
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3001:3000" # Expose di 3001 karena 3000 dipakai app
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks:
      - monitoring-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3 